// Checked against vendor API docs on 2026-09-23.
// Context and output ceilings are the published limits. maxInputTokens leaves
// the output ceiling inside that window so the profile stays valid.

function limits(contextWindow, maxOutputTokens) {
  return {
    contextWindow,
    maxOutputTokens,
    maxInputTokens: contextWindow - maxOutputTokens,
  };
}

const STANDARD_OUTPUT = 8192;

function withContextChoice(
  maxContext,
  maxOutput,
  standardContext = 128000,
  standardLabel = "常用",
) {
  const extendedOutput = Math.min(maxOutput, maxContext - 1);
  const standardOutput = Math.min(STANDARD_OUTPUT, standardContext - 1);
  const choices = [
    {
      label: `${standardLabel} ${standardContext / 1000}K`,
      ...limits(standardContext, standardOutput),
    },
    {
      label: "百万上下文",
      ...limits(maxContext, extendedOutput),
    },
  ];
  return { contextWindows: choices, ...choices[0] };
}

const shared = {
  embedding: false,
  embeddingModel: "",
  timeoutMs: 120000,
  system: true,
  json: true,
  tools: true,
};

export const EFFORT_LABELS = {
  none: "关闭",
  minimal: "极低",
  low: "低",
  medium: "中",
  high: "高",
  xhigh: "极高",
  max: "最深",
};

export const MODEL_CATALOG = [
  {
    id: "deepseek-flash",
    vendor: "DeepSeek",
    label: "DeepSeek V4.1 Flash",
    summary:
      "当前 Flash。上下文 1M，输出上限 384K，默认可思考（high），支持看图。",
    provider: "deepseek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-flash",
    ...withContextChoice(1000000, 384000),
    ...shared,
    vision: true,
    thinkingStyle: "deepseek",
    tokenField: "max_tokens",
    reasoningEfforts: ["none", "low", "high", "max"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 1,
  },
  {
    id: "deepseek-v4-pro",
    vendor: "DeepSeek",
    label: "DeepSeek V4 Pro",
    summary:
      "V4-Pro-0813。上下文 1M，输出上限 384K，默认可思考（high），仅文本。",
    provider: "deepseek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-v4-pro",
    ...withContextChoice(1000000, 384000),
    ...shared,
    vision: false,
    thinkingStyle: "deepseek",
    tokenField: "max_tokens",
    reasoningEfforts: ["none", "low", "high", "max"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 1,
  },
  {
    id: "mimo-v2.6-pro",
    vendor: "小米 MiMo",
    label: "MiMo V2.6 Pro",
    summary:
      "当前旗舰。上下文 1M，输出上限 128K，思考默认开启，可看图、音视频。",
    provider: "mimo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2.6-pro",
    ...withContextChoice(1048576, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "mimo",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "high"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "mimo-v2.6-flash",
    vendor: "小米 MiMo",
    label: "MiMo V2.6 Flash",
    summary:
      "当前高速全模态。上下文 1M，输出上限 128K，思考默认开启，适合高频调用。",
    provider: "mimo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2.6-flash",
    ...withContextChoice(1048576, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "mimo",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "high"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "glm-5.3",
    vendor: "智谱 GLM",
    label: "GLM-5.3",
    summary:
      "当前旗舰。上下文 1M，输出上限 128K，思考不能关闭，默认最深（max），仅文本。",
    provider: "glm",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-5.3",
    ...withContextChoice(1000000, 131072),
    ...shared,
    vision: false,
    thinkingStyle: "glm",
    tokenField: "max_tokens",
    reasoningEfforts: ["low", "high", "max"],
    reasoningEffort: "max",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "glm-5.3-flash",
    vendor: "智谱 GLM",
    label: "GLM-5.3 Flash",
    summary:
      "当前轻量多模态。上下文 1M，输出上限 128K，思考不能关闭，默认最深（max）。",
    provider: "glm",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-5.3-flash",
    ...withContextChoice(1000000, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "glm",
    tokenField: "max_tokens",
    reasoningEfforts: ["low", "high", "max"],
    reasoningEffort: "max",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "kimi-k3",
    vendor: "Kimi",
    label: "Kimi K3",
    summary:
      "当前旗舰。上下文 1M，默认输出 128K，思考不能关闭，默认最深（max）。国内接口，国际站可改 api.moonshot.ai。",
    provider: "kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "kimi-k3",
    ...withContextChoice(1048576, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "kimi-effort",
    tokenField: "max_completion_tokens",
    omitSampling: true,
    reasoningEfforts: ["low", "high", "max"],
    reasoningEffort: "max",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "kimi-k2.6",
    vendor: "Kimi",
    label: "Kimi K2.6",
    summary:
      "通用多模态。上下文 256K，思考默认开启，可关闭。国内接口，国际站可改 api.moonshot.ai。",
    provider: "kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "kimi-k2.6",
    ...limits(262144, 32768),
    ...shared,
    vision: true,
    thinkingStyle: "kimi-toggle",
    tokenField: "max_tokens",
    omitSampling: true,
    reasoningEfforts: ["none", "high"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 0.95,
  },
  {
    id: "gpt-6-astra",
    vendor: "OpenAI",
    label: "GPT-6 Astra",
    summary:
      "当前旗舰 gpt-6-astra。上下文 1.05M，输出上限 128K。思考无关闭档；官方未写默认档，这里预填 medium。",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-6-astra",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "gpt-6-sol",
    vendor: "OpenAI",
    label: "GPT-6 Sol",
    summary:
      "复杂编码和智能体。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭，可看图。",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-6-sol",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "gpt-6-luna",
    vendor: "OpenAI",
    label: "GPT-6 Luna",
    summary:
      "高频轻量。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭，可看图。",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-6-luna",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "gpt-5.6-sol",
    vendor: "OpenAI",
    label: "GPT-5.6 Sol",
    summary:
      "专业旗舰，别名 gpt-5.6。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭。",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-5.6-sol",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "gpt-5.6-luna",
    vendor: "OpenAI",
    label: "GPT-5.6 Luna",
    summary: "高性价比。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭。",
    provider: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-5.6-luna",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "qwen3.8-max",
    vendor: "通义千问",
    label: "Qwen3.8 Max",
    summary:
      "当前旗舰，快照 qwen3.8-max-0902。上下文 1M，输出上限 128K，思考默认开启，可看图和视频。",
    provider: "qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen3.8-max",
    ...withContextChoice(1000000, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "qwen",
    tokenField: "max_tokens",
    reasoningEfforts: ["none", "high"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 1,
  },
  {
    id: "qwen3.8-flash",
    vendor: "通义千问",
    label: "Qwen3.8 Flash",
    summary: "当前轻量。上下文 1M，输出上限 128K，思考默认开启，可看图和视频。",
    provider: "qwen",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen3.8-flash",
    ...withContextChoice(1000000, 131072),
    ...shared,
    vision: true,
    thinkingStyle: "qwen",
    tokenField: "max_tokens",
    reasoningEfforts: ["none", "high"],
    reasoningEffort: "high",
    temperature: 1,
    topP: 1,
  },
  {
    id: "bedrock-gpt-6-astra",
    vendor: "亚马逊 Bedrock",
    label: "GPT-6 Astra",
    summary:
      "Bedrock Runtime（us-east-1），模型名 us.openai.gpt-6-astra。上下文 1.05M，输出上限 128K。思考无关闭档，预填 medium。",
    provider: "bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
    model: "us.openai.gpt-6-astra",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "bedrock-gpt-6-sol",
    vendor: "亚马逊 Bedrock",
    label: "GPT-6 Sol",
    summary:
      "Bedrock Runtime（us-east-1），模型名 us.openai.gpt-6-sol。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭。",
    provider: "bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
    model: "us.openai.gpt-6-sol",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "bedrock-gpt-6-luna",
    vendor: "亚马逊 Bedrock",
    label: "GPT-6 Luna",
    summary:
      "Bedrock Runtime（us-east-1），模型名 us.openai.gpt-6-luna。上下文 1.05M，输出上限 128K，思考默认 medium，可关闭。",
    provider: "bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
    model: "us.openai.gpt-6-luna",
    ...withContextChoice(1050000, 128000, 272000, "标准"),
    ...shared,
    vision: true,
    thinkingStyle: "openai",
    tokenField: "max_completion_tokens",
    reasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
    reasoningEffort: "medium",
    temperature: 1,
    topP: 1,
  },
  {
    id: "custom",
    vendor: "自定义",
    label: "自定义兼容接口",
    summary: "OpenAI 兼容接口。上下文先按 128K 填，思考档可按供应商再改。",
    provider: "custom",
    baseUrl: "",
    model: "",
    ...limits(128000, 8192),
    embedding: false,
    embeddingModel: "",
    timeoutMs: 90000,
    system: true,
    json: true,
    tools: false,
    vision: false,
    thinkingStyle: "openai",
    tokenField: "max_tokens",
    reasoningEfforts: [
      "none",
      "minimal",
      "low",
      "medium",
      "high",
      "xhigh",
      "max",
    ],
    reasoningEffort: "none",
    temperature: 0.85,
    topP: 1,
  },
];

export const MODEL_PRESETS = {
  custom: { label: "自定义兼容接口", baseUrl: "", model: "" },
  deepseek: {
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-flash",
  },
  openai: {
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-6-astra",
  },
  bedrock: {
    label: "亚马逊 Bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1",
    model: "us.openai.gpt-6-astra",
  },
  qwen: {
    label: "通义千问",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen3.8-max",
  },
  moonshot: {
    label: "Kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "kimi-k3",
  },
  kimi: {
    label: "Kimi",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "kimi-k3",
  },
  zhipu: {
    label: "智谱 GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-5.3",
  },
  glm: {
    label: "智谱 GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-5.3",
  },
  mimo: {
    label: "小米 MiMo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2.6-pro",
  },
  siliconflow: {
    label: "SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    model: "",
  },
  openrouter: {
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "",
  },
};

export const REASONING_EFFORTS = [
  { id: "none", label: "关闭" },
  { id: "minimal", label: "极低" },
  { id: "low", label: "低" },
  { id: "medium", label: "中" },
  { id: "high", label: "高" },
  { id: "xhigh", label: "极高" },
  { id: "max", label: "最深" },
];
